[project]
name = "ds4se"
description = "data science for software engineers"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "altair>=6.1.0",
    "mccole",
    "polars>=1.33.0",
    "ruff>=0.15.13",
    "taskipy>=1.14.1",
]

[tool.ruff]
exclude = [
    "unused"
]

[tool.taskipy.tasks.bib]
help = "Check bibliography entries."
cmd = "mccole bib"

[tool.taskipy.tasks.clean]
help = "Clean up generated and cache files."
cmd = """
    find . -type f -name '*~' -exec rm {} \\;
    find . -type d -name __pycache__ | xargs rm -rf
    find . -type d -name .ruff_cache | xargs rm -rf
"""

[tool.taskipy.tasks.check]
help = "Check code and project."
cmd = """
    mccole check --src . --dst docs
    typos *.md */*.md
    ruff check .
"""

[tool.taskipy.tasks.serve]
help = "Serve generated HTML."
cmd = "python -m http.server -d docs"

[tool.taskipy.tasks.site]
help = "Build HTML."
cmd = """
    mccole build --src . --dst docs
    touch docs/.nojekyll
"""

[tool.mccole]
brand = "DS4SE"
repo = "https://github.com/gvwilson/ds4se"
skips = [
  "**/*~",
  "**/__pycache__/**",
  "*.csv",
  "*.js",
  "*.py",
  "*.sh",
  "*.tbl",
  "*.txt",
  "*.xlsx",
  "*/data/*",
  "docs/**",
  "_extras/**",
  "log/**",
  "unused/**",
  "uv.lock"
]
