[project]
name = "ds4se"
description = "data science for software engineers"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "linkchecker",
    "mccole",
    "polars"
]

[tool.mccole]
skips = [
    "*~",
    "*/data/*",
    "*.csv",
    "*.js",
    "*.py",
    "*.sh",
    "*.tbl",
    "*.txt",
    "*.xlsx",
    "extras/**",
    "unused/**",
    "uv.lock"
]

[tool.mccole.renames]
"README.md" = ""
"CODE_OF_CONDUCT.md" = "conduct"
"CONTRIBUTING.md" = "contrib"
"LICENSE.md" = "license"
